// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_j7ykUfvGEjmRO2aWd40YJDlNAb1r0Vo',
    appId: '1:781190414818:web:f54d7880ab005d5c6b39bb',
    messagingSenderId: '781190414818',
    projectId: 'true-barber-58d7c',
    authDomain: 'true-barber-58d7c.firebaseapp.com',
    storageBucket: 'true-barber-58d7c.firebasestorage.app',
    measurementId: 'G-X929W05RYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqnLQQn0pgkry6wwkpTpIWSRWaOFnmTaY',
    appId: '1:781190414818:android:446bb711f5464b3e6b39bb',
    messagingSenderId: '781190414818',
    projectId: 'true-barber-58d7c',
    storageBucket: 'true-barber-58d7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Cm7X6h2hgnVLCoItyrXQP5y_JAu49uM',
    appId: '1:781190414818:ios:af786e329d8600d16b39bb',
    messagingSenderId: '781190414818',
    projectId: 'true-barber-58d7c',
    storageBucket: 'true-barber-58d7c.firebasestorage.app',
    iosBundleId: 'com.example.theRegular',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Cm7X6h2hgnVLCoItyrXQP5y_JAu49uM',
    appId: '1:781190414818:ios:af786e329d8600d16b39bb',
    messagingSenderId: '781190414818',
    projectId: 'true-barber-58d7c',
    storageBucket: 'true-barber-58d7c.firebasestorage.app',
    iosBundleId: 'com.example.theRegular',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_j7ykUfvGEjmRO2aWd40YJDlNAb1r0Vo',
    appId: '1:781190414818:web:d416fdd43d78b94c6b39bb',
    messagingSenderId: '781190414818',
    projectId: 'true-barber-58d7c',
    authDomain: 'true-barber-58d7c.firebaseapp.com',
    storageBucket: 'true-barber-58d7c.firebasestorage.app',
    measurementId: 'G-58S7FPT7WW',
  );
}
